=== lainigian/2018_2019_XMLStazioneMeteo/stazione_meteo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="tipoCoordinate">
		<xs:sequence>
			<xs:element name="longitudine">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="-180"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="latitudine">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="-90"/>
						<xs:maxInclusive value="90"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
				
	<xs:complexType name="tipoRilevazione">
		<xs:sequence>
			<xs:element name="ora" type="xs:time"/>
			<xs:element name="temperatura">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="-50"/>
						<xs:maxInclusive value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="umidita">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="pressione">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="700"/>
						<xs:maxInclusive value="1200"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="velocitaVento">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="500"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="direzioneVento">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="359"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="pioggia">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="stazione">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id_stazione" type="xs:string"/>
				<xs:element name="coordinate" type="tipoCoordinate"/>
				<xs:element name="data" type="xs:date"/>
				<!--elenco rilevazioni-->
				<xs:element name="rilevazione" type="tipoRilevazione" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		

</xs:schema>

=== lainigian/2018_2019_XMLStazioneMeteo/stazione_meteo.xml
<?xml version="1.0"?>
<stazione
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="stazione_meteo.xsd">
	<id_stazione>ST01</id_stazione>
	<coordinate>
		<longitudine>10.003422</longitudine>
		<latitudine>45.332211</latitudine>
	</coordinate>
	<data>2019-02-11</data>
	<rilevazione>
		<ora>00:00:00</ora>
		<temperatura>3</temperatura>
		<umidita>55</umidita>
		<pressione>900</pressione>
		<velocitaVento>23</velocitaVento>
		<direzioneVento>48</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
	<rilevazione>
		<ora>04:00:00</ora>
		<temperatura>2.5</temperatura>
		<umidita>58</umidita>
		<pressione>990</pressione>
		<velocitaVento>32</velocitaVento>
		<direzioneVento>50</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
	<rilevazione>
		<ora>08:00:00</ora>
		<temperatura>6</temperatura>
		<umidita>50</umidita>
		<pressione>1000</pressione>
		<velocitaVento>10</velocitaVento>
		<direzioneVento>44</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
	<rilevazione>
		<ora>12:00:00</ora>
		<temperatura>9</temperatura>
		<umidita>65</umidita>
		<pressione>1020</pressione>
		<velocitaVento>23</velocitaVento>
		<direzioneVento>48</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
	<rilevazione>
		<ora>16:00:00</ora>
		<temperatura>5</temperatura>
		<umidita>55</umidita>
		<pressione>900</pressione>
		<velocitaVento>40</velocitaVento>
		<direzioneVento>44</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
	<rilevazione>
		<ora>20:00:00</ora>
		<temperatura>4</temperatura>
		<umidita>54</umidita>
		<pressione>1024</pressione>
		<velocitaVento>12</velocitaVento>
		<direzioneVento>48</direzioneVento>
		<pioggia>0</pioggia>	
	</rilevazione>
</stazione>
